import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { Navbar } from "../components/Navbar"
import { Transactions } from "../components/Transactions"

import { data } from "../utils/data"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FinTech Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <h3>{data[0].bankName}</h3>
        <Transactions/>
      </main>
    </div>
  )
}
